services:
  warp-alpine:
    build:
      context: .
      dockerfile: docker/Dockerfile.alpine
    image: warp:alpine

  warp-debian:
    build:
      context: .
      dockerfile: docker/Dockerfile.debian
    image: warp:debian

  warp-fedora:
    build:
      context: .
      dockerfile: docker/Dockerfile.fedora
    image: warp:fedora
